upload_path: "/static/uploads/:year:/:month:/:day:"
frontmatter_file_url_template: "/uploads/:year:/:month:/:day:"
body_file_url_template: "/uploads/:year:/:month:/:day:"
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url: http://ajnouri.github.io/webhook
sections:
  posts:
    default_front_matter_template: posts
  pages:
    default_front_matter_template: pages
version: 0.31.1
---
